Documentation:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - db/**/*
    - config/**/*
    - script/**
    - 'Rakefile'
    - 'config.ru'

ClassLength:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'test/test_helper.rb'

Style/ClassAndModuleChildren:
  Enabled: false

# Temporarily disabling the following. At this point they've been resolved
# as much as they can be without doing things that might implicate test
# coverage.
Metrics/MethodLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/Validation:
  Enabled: false
