version: '2'

services:
  postgres:
    image: 'postgres:9.6'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=so_wow

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

volumes:
  postgres:
