services:
  postgres:
    image: 'postgres:14.6'
    tmpfs:
      - '/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=brkmn_test
      - POSTGRES_PASSWORD=so_wow
      - POSTGRES_DB=brkmn_test

  website:
    depends_on:
      - postgres
    build: .
    ports:
      - '5656:3000'
    volumes:
      - '.:/app'
    environment:
      - RAILS_ENV=test
