services:
  postgres:
    image: 'postgres:14'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      - '.:/app'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}

  app:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '5656:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env.development'

volumes:
  postgres:
