version: '2'

services:
  postgres:
    image: 'postgres:14.6'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=so_wow
      - POSTGRES_DB=brkmn

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '5656:3000'
    volumes:
      - '.:/app'

volumes:
  postgres:
