version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Setup filesystem
          command: |
            sudo chown -R 1000 .
      - run:
          name: Run Docker containers
          command: |
            docker-compose -f docker/docker-compose.test.yml up -d
      - run:
          name: Tests
          command: docker-compose -f docker/docker-compose.test.yml exec app bash -c "yarn install && yarn run build:css && bundle install && RAILS_ENV=test rake db:drop db:create db:migrate && bundle exec rspec"
