services:
  db:
    image: 'postgres:14'
    volumes:
      - 'db:/var/lib/postgresql/data'
      - '.:/app'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}

  app:
    depends_on:
      - 'db'
    build: .
    ports:
      - '8507:3000'
      - '8517:1080' # Mailcatcher
    volumes:
      - '.:/app'
    env_file:
      - '.env.development'

volumes:
  db:
