services:
  db:
    image: 'postgres:14'
    volumes:
      - 'db:/var/lib/postgresql/data'
      - '.:/app'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8507:3000'
      - '8517:1080' # Mailcatcher
    volumes:
      - '..:/app'
    restart: always
    environment:
      - APP_ENV=development

volumes:
  db:
