services:
  db:
    image: 'postgres:14.6'
    tmpfs:
      - '/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  website:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        RUBY_VERSION: 3.3.3
        NODE_VERSION: 22.9.0
        APP_ENV: test
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5656:3000'
    volumes:
      - '..:/app'
      - '/app/tmp'
    env_file:
      - ../.env.test
    environment:
      DATABASE_HOST: db
